def test_success():
    return

def test_failure():
    raise Exception("Custom error message")